### ISSUE TITLE
problem with z-index 

### ISSUE THREAD

**Issue by matinwd** [Alexeykhr/vue-stripe-menu#109]
First of all thanks for ur good library.
Why z-index does not work and drop down menu.
as u can see
![2020-02-24_0-30-57](https://user-images.githubusercontent.com/52950867/75119976-fbf13f80-569c-11ea-95cf-e8f6374940a7.png)
the menu is under the section and how can i solve it?

**Comment by matinwd** [comment]
setting the z-index for other sections does not work. i tried it, and i can not set the z-index for this menu

**Comment by Alexeykhr** [comment]
It's hard to say so, but try adding:

```
.vsm-menu {
  position: relative;
  z-index: 99999;
}
```

**Comment by 001101** [comment]
had the same issue, would be nice if you could push it, drove me nuts for a day =P
