### ISSUE TITLE
Decimal position values

### ISSUE THREAD

**Issue by aiankile** [Alexeykhr/vue-stripe-menu#135]
In 1.2.9 the translate-x value on vsm-dropdown-container can get decimal pixel values - which results in noticeble font blurring.

In 1.2.4 the issue cannot be reproduced. As far as I can see, the rounding was - probably unintentionally - removed in https://github.com/Alexeykhr/vue-stripe-menu/commit/ec99f8224b38708983ebd5f3ab37a9ddefe3f32c, with the revamp of calc logic.

**Comment by Alexeykhr** [comment]
Hi, thanks for the issue, I’ll fix the error :)

**Comment by aiankile** [comment]
Thanks for the quick fix!
