### ISSUE TITLE
demo is error

### ISSUE THREAD

**Issue by Nacho-Neko** [Alexeykhr/vue-stripe-menu#142]
Nodejs : v14.0.0
Vue : @vue/cli 4.3.1

Show results：
![Y6R_@} 9LAFM~7$86_J~X}E](https://user-images.githubusercontent.com/30208197/81272892-b380d580-9080-11ea-9e80-712eda4a6ec0.png)

**Comment by HanaForward** [comment]
![VYO(@P0UC_4LEMSA1U %8G3](https://user-images.githubusercontent.com/30208197/81273250-30ac4a80-9081-11ea-8461-27f06b8bc376.png)

**Comment by Alexeykhr** [comment]
The demo code is a skeleton for a quick start, but it is almost empty. Here is a more complete demo:
https://codepen.io/Alexeykhr/pen/YzPKxpX

**Comment by diomed** [comment]
it would probably be more convenient for beginners for demo to be filled with lorem ipsum data so one could simply edit it.

**Comment by Alexeykhr** [comment]
Yes, I agree, I will think about it

**Comment by Alexeykhr** [comment]
Well, I didn’t really figure out how to do it better, so I just added a few styles: D
But it looks better than it was.
