### ISSUE TITLE
Possibility add another event by default (click) ?

### ISSUE THREAD

**Issue by anthon97** [Alexeykhr/vue-stripe-menu#180]
Hi.
Thank you for great work, awesome component.

I faced with a problem where it was necessary to call dropdowns by click event by default.

I found not the most best solution, but it works...

```javascript
onMounted(() => {
      refs.VsmMenu.unregisterGlobalEvents();

      refs.VsmMenu.hasDropdownEls.forEach((el) => {
        const currentElement = el;
        const cloneElement = currentElement.cloneNode(true);

        currentElement.parentNode.replaceChild(cloneElement, currentElement);

        cloneElement.addEventListener('click', (event) => {
          event.preventDefault();
          
          refs.VsmMenu.toggleDropdown(cloneElement);
      });
    });
});
```
Are there any plans to make a choice of the event call by default?

**Comment by Alexeykhr** [comment]
Thank you for the issue, I did not plan to add the event "by click" initially, but later I will see the code how easy it can be added

**Comment by Alexeykhr** [comment]
@anthon97 Hi, i added new **handler** props. Can you check?

```vue
<vsm-menu handler="click" />
```

https://github.com/Alexeykhr/vue-stripe-menu#menu-props

[On the site](https://alexeykhr.github.io/vue-stripe-menu/), you can switch (top-right link) and check.

**Comment by anthon97** [comment]
@Alexeykhr, thank you for paying attention to my problem.

I`ll try soon
