### ISSUE TITLE
Conflicts with Nuxt/Vuetify

### ISSUE THREAD

**Issue by ConnorOnTheWeb** [Alexeykhr/vue-stripe-menu#192]
This is what I'm getting out of the gate:

<img width="1376" alt="Screen Shot 2020-11-02 at 1 48 33 PM" src="https://user-images.githubusercontent.com/28314904/97922948-1bebff00-1d12-11eb-882d-90e1195e8488.png">

Fresh install of Nuxt with Vuetify, vue-stripe-menu is added as a plugin. Example code is inserted as a AppNav.vue component included in the default layout.

Not sure what's conflicting. Is there an existing fix for this?

**Comment by Alexeykhr** [comment]
Hi, not sure if there is a bug here. It seems that there is simply no style (in this component are very few own styles), more emphasis on js logic.

Can you copy the [styles below <script>](https://github.com/Alexeykhr/vue-stripe-menu#basic-demo), or from [this example](https://codepen.io/Alexeykhr/pen/YzPKxpX)? Or if there is an error, show the text :)

**Comment by ConnorOnTheWeb** [comment]
Wow, not sure what I was doing the previous times but it worked perfectly this time around. Loving it, thank you!
