### ISSUE TITLE
Improved docs or handling for closing the mobile menu

### ISSUE THREAD

**Issue by djbusstop** [Alexeykhr/vue-stripe-menu#193]
Was having trouble figuring out how to close the mobile menu programatically. On desktop one can bind to the ref method `closeDropdown()`, but for mobile there's no such method. For mobile, it's possible to bind a v-model to the `vsm-mob` component and switch it to true or false programatically. However, `closeDropdown()` would make more sense as handling the mobile dropdown as well. Or at least put in the docs that one can bind `v-model` to `vsm-mob`.

**Comment by Alexeykhr** [comment]
Added `closeDropdown()` method [1.5.0].
