### ISSUE TITLE
Question about mobile 

### ISSUE THREAD

**Issue by daugaard47** [Alexeykhr/vue-stripe-menu#21]
Currently viewing on my phone, but the demo doesn't show a mobile version of the navigation. Do you have any plans to incorporate this?

**Comment by Alexeykhr** [comment]
Initially, I did not plan to write anything on the mobile phone. I understand that you have a hamburger menu?

**Comment by daugaard47** [comment]
No I don't have the hamburger menu. That is what I was asking. Do you plan to do the responsive stripe menu? 
Similar to this:
![menu-mobile](https://user-images.githubusercontent.com/3165203/67229036-787ec380-f408-11e9-8e31-d3e81556a2c1.JPG)


If not, would you accept a pull request If I did it for you?

**Comment by Alexeykhr** [comment]
Yeah, as I understand it, this will most likely go as a separate component that will be connected by the user to the main slot with custom content. I can implement, but I can also accept PR :)

**Comment by daugaard47** [comment]
Okay thanks for the quick response and for this great component.

**Comment by Alexeykhr** [comment]
Thanks for the issue, I will then implement it

**Comment by daugaard47** [comment]
Hey you did the mobile nav. Looks amazing. Thanks so much!

**Comment by Alexeykhr** [comment]
Haha, thanks :)
