### ISSUE TITLE
How I can use in Vue 2

### ISSUE THREAD

**Issue by ricar2ce** [Alexeykhr/vue-stripe-menu#220]
Hi, how can i use it in vue 2, i have a project in vue 2 and i am getting the following error : 
"TypeError: Cannot read property 'element' of undefined",
and i guess it is because i am using that version of vue, some help please 
thanks

**Comment by Alexeykhr** [comment]
Hi you need to install the library from [vue2](https://github.com/Alexeykhr/vue-stripe-menu/tree/vue2) branch:

```bash
$ npm i vue-stripe-menu@1.5.0
// or
$ yarn add vue-stripe-menu@1.5.0
```
