### ISSUE TITLE
 Duplicate presence of slot "default" found in the same render tree - this will likely cause render errors.

### ISSUE THREAD

**Issue by Thoimanich** [Alexeykhr/vue-stripe-menu#31]
[Vue warn]: Duplicate presence of slot "default" found in the same render tree - this will likely cause render errors. This error is occurred when i try run the simple example given in the docs
 "vue-stripe-menu": "^1.0.0",
 "vuex": "^3.0.1",
 "vue": "^2.5.17"

**Comment by Alexeykhr** [comment]
I just added an example on Codepen and don't see any mistakes:
[https://codepen.io/Alexeykhr/pen/zYYzxpv](https://codepen.io/Alexeykhr/pen/zYYzxpv)

Does your code also look like?
