### ISSUE TITLE
real demo

### ISSUE THREAD

**Issue by diomed** [Alexeykhr/vue-stripe-menu#48]
hi 

could we get real working demo, 
with proper links and images beside them
instead of placeholders?

**Comment by Alexeykhr** [comment]
Hi, yes, I think within a few days I will implement this on Сodepen and add a link to the documentation

**Comment by diomed** [comment]
may I contact you on mail for one small job, soon? 
involving implementing this somewhere

**Comment by Alexeykhr** [comment]
I'm not sure I’ll take it, too little time at the moment, but to be sure I'll get a demo :)

**Comment by Alexeykhr** [comment]
Well, something like this :)
Code: https://codepen.io/Alexeykhr/pen/YzPKxpX
Full: https://codepen.io/Alexeykhr/full/YzPKxpX

**Comment by diomed** [comment]
yes, great! thank you!
