### ISSUE TITLE
Pass menu data

### ISSUE THREAD

**Issue by gololobov-dev** [Alexeykhr/vue-stripe-menu#74]
Hello Alexey,
First of all thank you for beautiful project. I have a question about passing data/links to dropdown list. How i can do this?
For example can i do this from data section, adding a child items to "Info"?
```
data () {
    return {
      menu: [
        { title: 'Info', dropdown: 'info', content: HorizontalPrimaryContent, secondary: HorizontalSecondaryContent },
      ]
    }
  }
```
Thank you!

**Comment by Alexeykhr** [comment]
Hello. All data in the dropdown menu can be added via default props:

```
<vsm-menu :menu="myMenu">
  <template #default="data">
    <div>Here are the links / blocks in the dropdown menu</div>
   </template>
</vsm-menu>
```

The component filters all menu items that have a drop-down list, and then iterates through them to this default props. In order not to write in this way:

```
<template #default="data">
  <div v-if="data.item.title === 'First title'">
    <!--Dropdown content for this title-->
  </div>
  <div v-if="data.item.title === 'Second title'">
    <!--Another dropdown content-->
  </div>
  <!--etc-->
</template>
```

You can create a separate component for each menu item, and through the dynamic `<component />` implement it in `<vsm-menu />`:

```
data() {
  return {
    menu: [
      { title: 'Second title', dropdown: 'first', component: FirstDropdownContent },
      { title: 'First title', dropdown: 'second', component: SecondDropdownContent },
    ]
  }
}
```

And add to the dropdown list:

```
<template #default="data">
  <component :is="data.item.component" />
</template>
```

I didn’t do any template for the drop-down list, because each one will have its own and it makes no sense to carry unused code. So the whole inner design of the dropdown content is up to you :)

**Comment by Alexeykhr** [comment]
You can copy a few styles from here, and see how it is implemented here.
[Codepen - Vue Stripe Menu - Real Demo](https://codepen.io/Alexeykhr/pen/YzPKxpX)

**Comment by Constantin-Gololobov** [comment]
Hi,
Thank you for your quick answer. I will try to implement this today.

**Comment by Constantin-Gololobov** [comment]
I just thing that it possible to keep all information about menu info in one file like this:
~~~
data () {
    return {
      menu: [
        { title: 'Group 1', dropdown: 'group1', content: 'default',
            primary: [
                 {title: 'Item1', url: '/item1',  text: '', icon: '', class: '', etc.},
                 {title: 'Item2', url: '/item2', text: '', icon: '', class: '', etc.},
                 {title: 'Item3', url: '/item3', text: '', icon: '', class: '', etc.},
           ]
        },
       { title: 'Group 2', dropdown: 'group2', content: 'vertical',
            primary: [
                 {title: 'Item1', url: '/item1', text: '', icon: '', class: '', etc.},
                 {title: 'Item2', url: '/item2', text: '', icon: '', class: '', etc.},
                 {title: 'Item3', url: '/item3', text: '', icon: '', class: '', etc.},
           ],
           secondary: [
                 {title: 'Item4', url: '/item1', text: '', icon: '', class: '', etc.},
                 {title: 'Item5', url: '/item2', text: '', icon: '', class: '', etc.},
                 {title: 'Item6', url: '/item3', text: '', icon: '', class: '', etc.},
           ]
        },
       { title: 'Group 3', dropdown: 'group3', content: 'horizontal',
            primary: [
                 {title: 'Item1', url: '/item1', text: '', icon: '', class: '', etc.},
                 {title: 'Item2', url: '/item2', text: '', icon: '', class: '', etc.},
                 {title: 'Item3', url: '/item3', text: '', icon: '', class: '', etc.},
            ],
           secondary: [
                 {title: 'Item4', url: '/item1', text: '', icon: '', class: '', etc.},
                 {title: 'Item5', url: '/item2', text: '', icon: '', class: '', etc.},
                 {title: 'Item6', url: '/item3', text: '', icon: '', class: '', etc.},
           ]
        },
      ]
    }
  }
~~~
In that way you can re-use this data in the footer menu, for example, or for mobile nav or another place. And managing all data from one place.
Is it possible to do something like this?

**Comment by Alexeykhr** [comment]
The appearance in the desktop and mobile versions can be radically different. As from the user.

I think the best option would be this:

- Create a component, for example: `BaseHeaderItem.vue`

```
<template>
  <div><!--Some logic/design--><slot /></div>
</template>

<script>
export default {
  props: {
    item: { type: Object, required: true }
  }
}
</script>
```

- Connect to the component:

```
<vsm-menu :menu="menu">
  <template #default="data">
    <base-header-item :item="data.item" />
  </template>
</vsm-menu>
```

Now all dropdown lists (for desktop) have a single view, which is fully customizable by the user. Also, create a component for responsive design. Transfer your current menu through props, and there it is at least recursively bypassing and displaying as it should.

You still have your current array and you manage it through props through your own components. How about this option? :)

**Comment by Constantin-Gololobov** [comment]
Ok, thanks for your advice. I will try to do that :)
