### ISSUE TITLE
router-link

### ISSUE THREAD

**Issue by infinitodk** [Alexeykhr/vue-stripe-menu#89]
For first-level items, how add links using router-link?

**Comment by Alexeykhr** [comment]
```
data() {
  return {
    menu: [{
      title: 'My link',
      element: 'router-link',
      attributes: {
        // to: '/',
        // or like Object
        to: { name: 'my-page1' }
      }
    }]
  }
}
```

**Comment by infinitodk** [comment]
Thanks!!

**Comment by infinitodk** [comment]
Hi,

Unfortunately the menu stops working if all links are router-link.

Seems like this part is the culprit.

`hasDropdownEls: function hasDropdownEls() {
      var links = this.$refs.links || [];
      return links.filter(function (el) {
        return el.classList.contains('vsm-has-dropdown');
      });
    },`

**Comment by infinitodk** [comment]
If there is no links, it throws an undefined error.

**Comment by infinitodk** [comment]
> TypeError: "el.classList is undefined"
    hasDropdownEls vue-stripe-menu.common.js:2370

**Comment by infinitodk** [comment]
Changing element to "div" or "span" or pretty much anything makes everything work.

**Comment by infinitodk** [comment]
Using latest versions of vue, this plugin, vue router.

**Comment by Alexeykhr** [comment]
Thanks, I found a problem, I will try to release a fix today

**Comment by Alexeykhr** [comment]
This should fix the problem https://github.com/Alexeykhr/vue-stripe-menu/pull/95

**Comment by infinitodk** [comment]
It works like a charm! Did you see my other question about donating?

**Comment by Alexeykhr** [comment]
Saw, thanks, but I don’t have any donation button :)

**Comment by infinitodk** [comment]
I want to support the development of this package, any other way?

**Comment by Alexeykhr** [comment]
Oh my god, I never did this, I didn’t even think that this would happen :)

**Comment by infinitodk** [comment]
Well, creating good software makes people want to support it. Got Paypal?

**Comment by Alexeykhr** [comment]
Yep, I added a button with a Ko-fi site, thanks again :)

**Comment by infinitodk** [comment]
It won't let me pay, just getting an error. Got paypal instead?

**Comment by Alexeykhr** [comment]
I saw that many people use Paypal me to get a link, but in my country it is not available :)

I found a donate button in the account, if this doesn’t help, it means there are some problems, I don’t know..

[Paypal Link](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=alexeykhr%40outlook.com&currency_code=USD&source=url)
