### ISSUE TITLE
problem to show sub menus

### ISSUE THREAD

**Issue by matinwd** [Alexeykhr/vue-stripe-menu#92]
![2020-01-29_12-28-48](https://user-images.githubusercontent.com/52950867/73342047-14835b00-4293-11ea-80c2-36960469898e.png)
what is wrong with this?
i copied your codes and i have this problem.
this is my code
  ```
data() {
            return {
                menu: [
                    { title: 'First item', dropdown: 'first' },
                    { title: 'Second item', dropdown: 'second' },
                    { title: 'No dropdown' }
                ]
            }
        }
        ,
        methods: {
            onOpenDropdown() {
                console.log('onOpenDropdown')
            }
            ,
            onCloseDropdown() {
                console.log('onCloseDropdown')
            }
        }
        
]




```

and this is the vue
```
<template>
<div>
        <vsm-menu :menu="menu">
            <template #default="data">
                <div>{{ data }}</div>
            </template>
        </vsm-menu>


    </div>
</template>
```

thanks for your help

**Comment by Alexeykhr** [comment]
CSS styles and in general all the logic for displaying a drop-down list is on the "client" side. Those. each menu may look different, so I did not include styles.

You can take ready-made styles, which I did as an example:
https://github.com/Alexeykhr/vue-stripe-menu/tree/master/demo/components

Or from another Codepen example:
https://codepen.io/Alexeykhr/pen/YzPKxpX

**Comment by matinwd** [comment]
oh i got confused. how can i use your example?

**Comment by Alexeykhr** [comment]
I mean, you need to style the drop-down menu yourself, as well as how it will look. In the examples, I made a separate component for each submenu:

```
data() {
  return {
    menu: [
      { title: 'Features', dropdown: 'dropdown1', content: MyImportedComponent }
    ]
  }
}
```

`MyImportedComponent.vue`

And the component already has html/js/styles. Well .. I hope I clearly said :)

**Comment by matinwd** [comment]
i could not work with this. could you make a good example? thanks for your great library.

**Comment by Alexeykhr** [comment]
Ok try this :)

You have a structure similar to:

`src/components/menu/BaseHeader.vue`

```vue
<template>
  <vsm-menu :menu="menu">
      <template #default="{ item }">
          <!--In this place, through the default slot on each iteration of your array (where there is a dropdown menu)-->
          <!--I pass an array object, and you output it as you want (here, through a dynamic component, etc)-->
          <!--https://vuejs.org/v2/guide/components-slots.html#Named-Slots-Shorthand-->
          <div>{{ item }}</div>
      </template>
  </vsm-menu>
</template>

<script>
export default {
  data() {
    return {
      menu: [
        { title: 'First item', dropdown: 'first' },
        { title: 'Second item', dropdown: 'second' },
        { title: 'No dropdown' }
      ]
    }
  }
}
</script>
```

For example, you want to add blocks/list to the dropdown menu like on Stripe.
You can create a separate component with a common structure and insert values through props/slots or for each menu item create your own unique component.
Actually, here is about the 2nd option.

Create a component for the first item in the menu:

`src/components/menu/FirstElementContent.vue`

```vue
<template>
  <div id="first-element-content">
    <!--You have complete freedom over how this particular menu item will be displayed-->
    <!--All sorts of circles, lists, other components, etc. using incoming props/slots/vuex/etc-->
    My Content
    <hr>
    <span>{{ item.title }}</span>
  </div>
</template>

<script>
export default {
  props: {
    // If you want to transfer your object from the menu
    // and do some manipulations based on it
    item: {
      type: Object,
      required: true
    }
  }
}
</script>

<style lang="scss" scoped>
#first-element-content {
  min-width: 300px;
  padding: 20px;
}

span {
  color: red;
}
</style>
```

Now connect our created component to our menu:

`src/components/menu/BaseHeader.vue`

```vue
<template>
  <vsm-menu :menu="menu">
      <template #default="{ item }">
          <!--In order not to write a lot of if, to display our component in the desired menu item, we use-->
          <!--https://vuejs.org/v2/guide/components-dynamic-async.html-->
          <component
            :is="item.component"
            :item="item"
          />
      </template>
  </vsm-menu>
</template>

<script>
import FirstElementContent from './FirstElementContent'

export default {
  data() {
    return {
      menu: [
        // Add a new component property, where we will add our new components for each menu item
        { title: 'First item', dropdown: 'first', component: FirstElementContent },
        { title: 'Second item', dropdown: 'second' },
        { title: 'No dropdown' }
      ]
    }
  }
}
</script>
```

The end result should be something like this:

![image](https://user-images.githubusercontent.com/14747569/75112726-29170100-564f-11ea-81b0-3b44a3c8ce6b.png)

That is, there are no ready-made styles as such, so that everything would look just like on the same Stripe website. You wrap this component in your common (somewhat unique) component and style it

**Comment by matinwd** [comment]
![2020-02-23_18-55-25](https://user-images.githubusercontent.com/52950867/75114774-2bd51e80-566e-11ea-9a1a-85f10c8dde03.png)
end result for me is this...

**Comment by matinwd** [comment]
Can u connect to my anydesk? for check this.

**Comment by Alexeykhr** [comment]
I think you are not importing styles. Do you have this line in js/sass/etc?

`import 'vue-stripe-menu/dist/vue-stripe-menu.css'`

**Comment by matinwd** [comment]
thanks it solved. for responsive what should i do?

**Comment by Alexeykhr** [comment]
Nothing :)

**Comment by matinwd** [comment]
very very helpful thanks bro :)
