### ISSUE TITLE
Support for Bootstrap

### ISSUE THREAD

**Issue by infinitodk** [Alexeykhr/vue-stripe-menu#93]
Using the menu in a bootstrap setup renders the submenu off by quite some pixels.

**Comment by Alexeykhr** [comment]
Can you explain a little more? :)

**Comment by infinitodk** [comment]
Hey,

Setting up the menu in Bootstrap 4 grid will make the submenu show with quite some offset. Using the menu outside of bootstraps grid will render the menu just fine even with bootstrap loaded. 

`<div class="container">
  <div class="row justify-content-md-center">
    <div class="col col-lg-2">
      Logo
    </div>
    <div class="col-md-auto">
      INSERT MENU HERE
    </div>
    <div class="col col-lg-2">
      Search
    </div>
  </div>
  <div class="row">
    <div class="col">
      1 of 3
    </div>
    <div class="col-md-auto">
      Variable width content
    </div>
    <div class="col col-lg-2">
      3 of 3
    </div>
  </div>
</div>`

**Comment by infinitodk** [comment]
https://codepen.io/christian-fynbo/pen/WNbqGqR

Here is an example

**Comment by infinitodk** [comment]
Will check tomorrow. Got a donation button somewhere?

**Comment by infinitodk** [comment]
Works like a charm!
