### ISSUE TITLE
Support for NuxtJS

### ISSUE THREAD

**Issue by TooColline** [Alexeykhr/vue-stripe-menu#94]
I am having a little trouble registering the components in NuxtJS. I've tried importing it explicitly to using it as a plugin, still not recognizing the ```<vsm-menu> or <vsm-mob>``` components. Kindly help out.

**Comment by Alexeykhr** [comment]
Can you try to install, as I already described in this issue?
https://github.com/Alexeykhr/vue-stripe-menu/issues/72

If it doesn't work out, let me know

**Comment by TooColline** [comment]
<img width="854" alt="Screenshot 2020-01-30 at 09 11 59" src="https://user-images.githubusercontent.com/38856515/73424696-a72e0380-4340-11ea-93b2-3c564f545454.png">
This is what am getting

**Comment by Alexeykhr** [comment]
The error is similar to this (below warning), although strange.
https://stackoverflow.com/questions/47534267/webpack-there-are-multiple-modules-with-names-that-only-differ-in-casing-but

Okay, I’ll take a test project on Nuxtjs later and see

**Comment by TooColline** [comment]
I've fixed the warning. It's the `"export 'default' (imported as 'VueStripeMenu') was not found in 'vue-stripe-menu'` and this `Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'`

**Comment by Alexeykhr** [comment]
No more problems? :)

**Comment by TooColline** [comment]
I still can't load the menu, it's the errors that I've highlighted above which I need help on

**Comment by TooColline** [comment]
Solved

**Comment by rublev** [comment]
```
vue.runtime.esm.js?2b0e:619 [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
```

**Comment by Alexeykhr** [comment]
> ```
> vue.runtime.esm.js?2b0e:619 [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
> ```

I just created a new project in nuxtjs, connected the library - there seems to be no problem in the library itself.

Can you provide a little more information? For example, maybe you wrap a component in a `<p />` element:

```vue
<template>
  <p>
    <vue-stripe-menu .. />
  </p>
</template>
```
